### ISSUE TITLE
Bug in graph.compute_fourier_basis

### ISSUE THREAD

**Issue by rodrigo-pena** [epfl-lts2/pygsp#53] opened 2019-06-04 15:09 UTC
When you call `graph.compute_fourier_basis(n_eigenvectors=k)`, only the first `k-1` eigenvectors are computed, because of the design of the function `sparse.linalg.eigsh`.  

In particular, we have as a consequence that `graph.set_coordinates(kind='laplacian_eigenmap2D')` sets `graph.coords` to a one-dimensional vector.

**Comment by mdeff** [comment] 2019-06-04 19:58
Thanks for reporting! Would you be so kind as sending a PR? :)

**Comment by mdeff** [comment] 2019-06-04 20:06
Actually, I think the problem is in `set_coordinates`. It [asks for two eigenvectors](https://github.com/epfl-lts2/pygsp/blob/8ce5bde39206129287375af24fdbcd7edddca8c5/pygsp/graphs/_layout.py#L95) when `kind='laplacian_eigenmap2D'` while it should ask for three as the first constant eigenvector is discarded. Isn't it? (BTW, why doesn't `self.U[:, 1:3]` raise an exception if there's only two eigenvectors?)

The [documentation of `scipy.sparse.linalg.eigsh`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) says:
> k : int, optional
>    The number of eigenvalues and eigenvectors desired. k must be smaller than N. It is not possible to compute all eigenvectors of a matrix.

**Comment by rodrigo-pena** [comment] 2019-06-06 06:47
Yes, it seems that the problem is in `set_coordinates`, because `graph.compute_fourier_basis(n_eigenvectors=2)` computes indeed the first 2 eigenvectors. However, we need at least 3, because the first one is trivial. Actually, there should be some functionality that detects how many trivial eigenvectors there are, and then returns the first two non-trivial ones.

As for your remark:

> BTW, why doesn't self.U[:, 1:3] raise an exception if there's only two eigenvectors?

if `self.U` has only two columns, numpy returns `self.U[:,1]` no matter the index `i` that you put in `self.U[:, 1:i]`, as long as `i` is larger than `self.U.shape[1]`.

I'll open a branch to fix the issue.

**Comment by mdeff** [comment] 2019-06-12 08:44
Fixed in #54.

**Closed by mdeff** 2019-06-12 08:44 UTC
